### ISSUE TITLE
Netflix Silverlight

### ISSUE THREAD

**Issue by kennedy** [mullvad/mullvad-browser#180] opened 2023-10-29 01:45 UTC
I attempted to watch Netflix on mullvad browser, was redirected to this page: [Silverlight plug-in isn't supported](https://help.netflix.com/en/node/2090)

Might be related to https://github.com/mullvad/mullvad-browser/issues/158.

**Comment by ruihildt** [comment] 2023-10-29 19:35
Closing as a duplicate of #158.

While for some reason Netflix think we have silverlight installed (we don't), Widevine DRM is not present and all DRM content related to it simply won't run.

**Closed** 2023-10-29 19:35 UTC
Labels: duplicate
