### ISSUE TITLE
Virus Total flags 3 detections for Mullvad installer.

### ISSUE THREAD

**Issue by BJZ3k** [mullvad/mullvad-browser#313] opened 2024-09-15 22:08 UTC
It's my first time downloading the browser interested in trying out. But when I uploaded the installer to virus total it comes back with 3 detections. Is this a normal false positive?
![mulvtdt](https://github.com/user-attachments/assets/065c11d2-4808-40d3-a598-d06ac6885e33)

**Comment by ruihildt** [comment] 2024-09-25 09:39
Closing as duplicate of #98.

These reports from antivirus come up periodically, and there's nothing we can do (except confirm everything is safe on our end).

We tried to contact some antivirus vendors, but they never responded.

**Closed by ruihildt** 2024-09-25 09:39 UTC
Labels: duplicate
