### ISSUE TITLE
[Request]: Improve Mullvad DNS, some sites can't be resolved their address.

### ISSUE THREAD

**Issue by Illegal-Services** [mullvad/mullvad-browser#125] opened 2023-08-17 10:17 UTC
Hello. For context, some websites are by default blocked in a country by the government trough ISPs default DNS applied to the home router of the user.
Changing DNS manually on the device connected to internet, or using apps like [Cloudflare Warp](https://cloudflarewarp.com/) can bypass this blocking.
I noticed that Mullvad Browser doesn't have this feature built-in.
Do you think it's possible to add a feature that makes it that we can choose the DNS we want to browse Mullvad with?
ex with [CloudFlare](https://1.1.1.1/):
1.1.1.1
1.0.0.1
or [Google](https://developers.google.com/speed/public-dns/):
8.8.8.8
8.8.4.4

**Comment by ruihildt** [comment] 2023-08-17 12:10
By default, Mullvad Browser uses Mullvad DoH (DNS over HTTPS), so should unblock any DNS block.

If that's not the case, can you post here what website are blocked? If you're not comfortable making these public, contact support@mullvad.net .

_____________________________________________

As in Firefox, you can setup a custom DoH.

You can find instructions by searching for `Firefox (desktop version) - before version 114.0` in this page: https://mullvad.net/en/help/dns-over-https-and-dns-over-tls/

**Comment by Illegal-Services** [comment] 2023-08-17 16:41
```
https://www.filmzenstream.online/
https://www2.filmstreaming.sh/
https://extreme-telechargement.name/
https://kickasstorrents.bz/
https://cpasmieux.in/
https://kickasstorrents.id/
https://fr.streamdeouf.org/
https://www.vipleague.st/
https://kickasstorrent.cr/
https://kickasst.net/
https://kick4ss.com/
https://kickass.onl/
https://wwv.time2watch.tv/
https://www.frenchstream.pw/
https://wvw.cpasmieux.site/
https://www.filmcomplet.cam/
https://www.film-streamingk.biz/
https://wwvv.voirfilms.bz/
https://kat.am/
https://v2.sportsurge.net/
https://v2.sportsurge.net/home2/
https://www.dpstream.tel/
https://www2.french-stream.app/
https://kkat.net/
https://thekat.cc/
https://kickasss.to/
https://katcr.to/
http://redi1.soccerstreams.net/
https://vww.voirseries.org/
https://kickasstorrents.to/
https://emule-island.eu/
https://kickasstorrents.cr/
https://01streaming.stream/
https://wvw.cpasmal.biz/
https://vv2.french-stream.is/
https://www.channelstream.es/
https://www.casinoonlinefrancais.fr/
https://kkickass.com/
https://intmusic.net/
http://streamcomplet.com/
http://ww1.filmstreaming.to/
https://nsw2u.com/
https://streaming-series.la/
```

here is the sample I had a problem with this morning, I'm wondering how this can be useful to you as you are probably not a French resident like I am, and therfull your government probably don't block some or even all of them but yeah

**Comment by Illegal-Services** [comment] 2023-08-17 16:44
> "By default, Mullvad Browser uses Mullvad DoH (DNS over HTTPS), so should unblock any DNS block."

well this didn't work for me:
![mullvadbrowser_2023-08-17_18-42](https://github.com/mullvad/mullvad-browser/assets/62464560/00cb3754-f73d-4ebf-8e60-8c91a7db3828)

**Comment by Illegal-Services** [comment] 2023-08-17 16:45
Oh I only noticed now the dropdown thingy, I'll try to input there 1.1.1.1 and see if it unblocks.. \:D

**Comment by Illegal-Services** [comment] 2023-08-17 16:54
Okay GOOD, that works fine now:)
Thanks for the answer also @ruihildt 

So I guess the new feature request I'm doing here is:

Make the both Mullvad DNS services:
Mullvad (Default)
Mullvad (Ad-blocking)

able to bypass those sites

**Comment by ruihildt** [comment] 2023-08-18 07:32
So I confirm that if you use Mullvad Browser default config, your DNS requests will go through Mullvad DoH and I can also confirm those websites are accessible through it.

You can verify the DNS used by going to https://mullvad.net/en/check or using the Mullvad Browser Extension.

I'll close thisissue as "can't reproduce" and will change its status if new elements are brought forward.

**Closed by ruihildt** 2023-08-18 07:32 UTC
Labels: question

**Comment by Illegal-Services** [comment] 2023-08-18 09:22
I confirm, I can't even reproduce it anymore. No idea why yesterday this thing didn't work for me.
But good thing it works, that is an awesome feature you got there!
