### ISSUE TITLE
Is Mullvad dropping Windows support?

### ISSUE THREAD

**Issue by RedSteel-1** [mullvad/mullvad-browser#326] opened 2024-10-01 22:38 UTC
If I undertstood everything correctly, the browser is dropping the support of Windows (7), but will continue supporting the malware so-called-windows (10 and above).
I would like to request to do the other way around - continue the support of Windows, and drop the support of malware so-called-windows.

If Mullvad is indeed a privacy/security-focused browser, this is what it would do, instead of leaving the users of Windows behind and keeping going with malware "os"es.
Certainly not the opposite.

**Comment by ruihildt** [comment] 2024-10-02 08:39
Windows 10/11 are not privacy friendly OS and versions below are not secure OS either, definitely not an ideal situation.

I personally encourage anyone feeling stuck with Windows to try out more privacy respecting OS that we support, like Debian, Fedora and Ubuntu. There are a lot of documentation available on the internet to get you started.

Closing as duplicate of #323.

**Closed by ruihildt** 2024-10-02 08:39 UTC
Labels: duplicate
