### ISSUE TITLE
The page is not being redirected correctly (Reddit)

### ISSUE THREAD

**Issue by Refold3547** [mullvad/mullvad-browser#311] opened 2024-09-13 02:58 UTC
Occasionally this bug appears when access the Reddit. In some cases, it happens in links from Google and other search engines; In others, in Reddit itself.

![Reddit mullvad](https://github.com/user-attachments/assets/6da2c33a-a870-4607-91f1-0f89e51b8627)

The only site that presents this problem is Reddit!

Other relevant information:
- Mullvad browser v.13.5.3
- I'm using VPN
- Extensions: Ublock with filters, Bitwarden, TWP (translator), Buster (Recaptcha), Mullvad extension
- Security level in Mullvad browser: disable
- DNS about https: disable

This bug is specific to Mulvad Browser, because I use Firefox with the same settings and this never happened.

I realized that a similar problem has been opened since last year, but seems to continue to the present day: https://github.com/orgs/mullvad/projects/15/views/1?pane=issue&itemId=41670593

**Comment by ruihildt** [comment] 2024-09-13 13:25
Closing as a duplicate of #167

**Closed by ruihildt** 2024-09-13 13:25 UTC
Labels: duplicate
