### ISSUE TITLE
Possible malware in latest alpha

### ISSUE THREAD

**Issue by SkewedZeppelin** [mullvad/mullvad-browser#242] opened 2024-04-07 18:41 UTC
Latest mullvad-browser-windows-x86_64-install-13.5a6.exe appears to drop a file LangDLL.dll which has 29 detections on VirusTotal: https://www.virustotal.com/gui/file/cda679d62e2852d900f412239e7c01a64a928db6c0cc03b8fa0c1eabdfe815c4

Reported here https://discuss.privacyguides.net/t/mullvad-browser-trojan-script-wacatac-b-ml/17753

**Comment by ruihildt** [comment] 2024-04-07 21:28
Thanks, I have forwarded to the devs and will follow up.

As mentioned in the thread, it's not the first time an installer is flagged by antivirus as a false positive.

**Comment by SkewedZeppelin** [comment] 2024-04-07 21:29
Thanks. I'm not too concerned, but 29 detections seemed a bit high for the usual false positive.

**Comment by ruihildt** [comment] 2024-04-07 21:31
As you may have seen elsewhere, ideally we would automatically submit new builds to get alerted as soon as possible, but it has not been a priority so far.

**Comment by SkewedZeppelin** [comment] 2024-04-08 12:48
@ruihildt 
appreciate the clarification

I suspect the real issue is that for whatever reason it is triggering Windows error reporting which makes it looks like it makes network connections which is why it gets flagged.

Is it perhaps compiled in some debug release mode?

**Comment by PieroV** [comment] 2024-04-08 20:19
> I suspect the real issue is that for whatever reason it is triggering Windows error reporting

What do you mean?
Have you seen crashes in that DLL?

In 13.5a4 we switched from GCC to Clang also for NSIS (we finally found a way to build the system plugin without the full GCC).
Also, we updated to NSIS 3.09, but in my various tests for the system installer I didn't get any crash.
NSIS isn't officially compatible with Clang (because of the system plugin, which uses a preprocessed assembly module), we have to patch it.
So, basically nobody has the same signature as us (still, our builds are reproducible byte by byte, so you can check that we're not adding malware to the builds).

Of course, we are ready to revert these changes, if needed.

However, we sign only the final installer, we don't sign any other binary, neither the ones that get installed, nor the ones that get extracted to a temporary directory to be used by the installer itself (like this `LangDLL.dll`).

>  Is it perhaps compiled in some debug release mode?

I _think_ we build in release. We don't really specify the mode, but if I understand correctly `scons` (the tool used by NSIS) builds in Release by default if I understand correctly.

**Comment by ruihildt** [comment] 2024-09-10 09:55
I will close this as latest alphas don't seem to trigger any antivirus flags.
See: https://www.virustotal.com/gui/file/440979e7ee48ad6300ca868435009f6ad9444d798c8dffbbe90c6a8d3ae9721c

Feel free to open a new issue if needed.

**Closed by ruihildt** 2024-09-10 09:55 UTC
Labels: bug, package
