### ISSUE TITLE
Sync storage is broken in webextensions

### ISSUE THREAD

**Issue by lamyergeier** [mullvad/mullvad-browser#26] opened 2023-04-04 14:26 UTC
Was able to install https://addons.mozilla.org/en-US/firefox/, such as https://addons.mozilla.org/en-US/firefox/addon/videospeed/

But was unable to access options as the extension is not shown in the browser bar (GUI). Somehow I accessed it using instructions given at [[Identifying Firefox extension by ID - Add-ons / addons.mozilla.org - Mozilla Discourse](https://discourse.mozilla.org/t/identifying-firefox-extension-by-id/74057/5)](https://discourse.mozilla.org/t/identifying-firefox-extension-by-id/74057/5), but the settings are not getting saved and extensions are not working.

**Comment by Minimalist73** [comment] 2023-04-04 14:32
The browser runs in "Private mode", it means that you need to explicitly tell the extension to run when that's the case. You can enable that under "details" when you click on an extension in "about:addons". Remember that adding new things will alter your fingerprint and will decrease the protection from the browser.

**Comment by lamyergeier** [comment] 2023-04-04 14:47
Thanks. That enables the extensions. But I am unable to save its settings (after I edit it when clicking the icon from the browser bar)

**Comment by cameck** [comment] 2023-04-21 21:00
@lamyergeier This is probably not a Mullvad issue, iirc there are weird things with IndexDB cache in Firefox when you run in private mode and probably that Add-on hasn't accounted for it would be my guess. I would try in Firefox private mode and see if you get the same result to start.

**Comment by ruihildt** [comment] 2023-04-21 21:38
I quickly looked at the code, and this is caused by the storage type the extension uses to save the settings.

As we entirely disable Firefox Sync, extensions can't use `[storage.sync](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync)` to save settings. They need to use the more common `[storage.local](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local)`.

As this is not a complex change to make, I'd suggest contacting the author to see if they would be willing to change it. (This would mean the preferences would not be saved to Firefox Sync unfortunately)

**Comment by ruihildt** [comment] 2023-10-19 12:55
Following #165, I have made further research and it seems that since we updated to Firefox ESR 115, storage sync error are handled differently and these extension settings don't work at all.

Go to `about:config`, accept and type `webextensions.storage.sync.enabled`.
This value is set to `false`, and you need to switch it to `true`.  (this should be safe to do because Firefox Sync is still disabled)

This might actually be fixing all storage sync errors (while not syncing obviously). 

@lamyergeier I tried videospeed, and the settings were correctly saved across browser restart. Can you confirm?

I will further investigate and open an issue upstream to see if we can flip that pref permanently.

**Comment by ruihildt** [comment] 2023-10-19 13:05
Related issue: https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/250

**Comment by ruihildt** [comment] 2024-03-05 12:35
This has been fixed in Mullvad Browser 13.0.4.

**Closed by ruihildt** 2024-03-05 12:35 UTC
Labels: bug, third-party extension

**Comment by lamyergeier** [comment] 2024-03-05 13:47
@ruihildt Yes it works.
