### ISSUE TITLE
Failed Tracking Query Parameter Tests on privacytests.org

### ISSUE THREAD

**Issue by iAnonymous3000** [mullvad/mullvad-browser#65] opened 2023-04-15 18:36 UTC
Mullvad Browser failed all tests in the "Tracking query parameter tests" category on privacytests.org. As a user, I'm concerned about any potential privacy issues this may cause.

Can you please investigate and address these failed tests? It would be helpful if you could explain what caused the failures and any steps you plan to take to mitigate them. Any updates or improvements made to the browser in response to these findings would be appreciated.

![image](https://user-images.githubusercontent.com/32236127/232247315-4ee51bc0-0dd6-4d9f-bfdc-772d57493295.png)

**Comment by Thorin-Oakenpants** [comment] 2023-04-16 01:07
duplicate of #8 
- see https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/158 & https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/166

**Comment by ruihildt** [comment] 2023-04-17 10:58
I confirm that this is due to the filter list not being enabled.
We're looking into it.

Closing in favor of #8

**Comment by Thorin-Oakenpants** [comment] 2023-04-17 11:48
I think you forgot to close it, Rui :)

**Closed** 2023-04-17 11:53 UTC
Labels: duplicate
