### ISSUE TITLE
Why does the releases page lack a Windows release?

### ISSUE THREAD

**Issue by eNkKVS4HxHc9jaq** [mullvad/mullvad-browser#86] opened 2023-05-05 19:52 UTC
There are only Linux and macOS builds but none for Windows. I think it should be included although Windows is a privacy nightmare.

**Comment by ruihildt** [comment] 2023-05-05 20:22
This is a duplicate of #85 .

This is a known issue, we'll fix it as soon as possible.

**Closed by ruihildt** 2023-05-05 20:22 UTC
