### ISSUE TITLE
Disable DNS over HTTPS as default setting

### ISSUE THREAD

**Issue by charlietango1** [mullvad/mullvad-browser#48] opened 2023-04-08 04:34 UTC
When I am connected to a VPN in Europe that normally uses a European DNS, Mullvad browser is routing my traffic through a DNS in the United States. When I disabled DNS over HTTPS, the browser correctly used the European DNS.

**Comment by neglector** [comment] 2023-04-15 03:49
I agree, since DoH isn't a good idea if you're already using VPN, and Mullvad Browser is supposed to be used with one by design. VPN providers have their own DNS servers, and this option seems redundant. It's the only pref that I have to manually change, which is problematic when it comes to fingerprintng.

**Comment by mullgit** [comment] 2023-09-23 18:31
I also found out that the preset Mullvad DNS-over-HTTPS (DOH) does not work well in terms of physical proximity (anycast?) to the nearest resolver. A comparison with Quad9 DOH https://dns.quad9.net/dns-query shows how much better it can work.

I would suggest: Quad9 as default setting. It will block malware and is geo-located very close to internet exchange points of presence.

**Comment by ruihildt** [comment] 2023-10-06 13:04
At the moment we have no plan to disable DoH as default in Mullvad Browser.
Especially since you're free to disable DoH and/or use a custom one.

I'll report to our team in charge of DoH the issues you have encountered.

**Comment by ruihildt** [comment] 2023-10-20 10:24
I will close this issue as we'll continue shipping Mullvad Browser without Mullvad DoH.

We're always looking into improving our DoH servers and are progressively improving the coverage.

**Closed by ruihildt** 2023-10-20 10:24 UTC
Labels: feature request, doh
