### ISSUE TITLE
Certain extensions recently stopped working.

### ISSUE THREAD

**Issue by ascisco** [mullvad/mullvad-browser#178] opened 2023-10-24 19:42 UTC
- MetaMask: Installs fine but presents cannot connect to server error when loading.
- PureVPN: Installs fine but shows, "cannot connect to server" error when connecting to chosen VPN server. 

About a month ago both of these plugin were working fine for me in Mullvad Browser. Not sure which update it was but both of these plugins no longer work properly. 
I have tested both of these plugins in Firefox and Librewolf, both work as they should.

**Comment by nev-al** [comment] 2023-10-31 12:01
After the last update 13.0.1 [metamask](https://addons.mozilla.org/en-US/firefox/addon/ether-metamask/) still does not work. Tor browser runs it with no problem.

**Comment by little-umbrellas** [comment] 2023-11-23 02:39
Same thing has happened to me, but with the [vimium-ff](https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/) add-on. After, I'd say 2 or so updates ago, it stopped working.

**Comment by nev-al** [comment] 2023-11-24 03:42
The update 13.0.4. Metamask does not work so far. It is in "everlasting loading" now.

**Comment by little-umbrellas** [comment] 2023-11-24 20:52
Vimium-FF works now, after the update.

**Comment by nev-al** [comment] 2023-12-06 18:26
13.0.6 all the same

**Comment by nev-al** [comment] 2023-12-19 18:53
13.0.7 nothing changed

**Comment by tjex** [comment] 2024-08-24 08:20
- Memex doesn't work for me. Can't login, or execute keybinds.
- Can't verify login between browser login and NordVPN desktop app.

**Comment by ruihildt** [comment] 2024-09-24 12:07
Sorry for not taking the time to answer this issue, and other regarding extensions,

To give you a better understanding of the situation, when an extension is not working on Mullvad Browser, it's hard to tell what's the cause. It could be:
- because Mullvad Browser is in Private Browsing Mode by default, which breaks some extension functionality
- because there's no sync storage, which creates error (though that should be fixed, if I remember well)
- because Mullvad Browser is based on the ESR and an extension is targeting a feature not present there
- because of a bug in the extension that doesn't manifest in Firefox regular release

Investigating takes time, and sometimes only the browser developers are able to do it. Since we don't recommend installing extensions, debugging individual extensions is not a priority, compared to improving the usability and privacy for the regular browsing experience.

So when there is some debugging, it is because I set aside some time for it, and it is limited to my knowledge. If an extension requires an account (like Metamask), then it's even more time consuming.

Does this mean we don't care about extension? We want everything that works on Firefox to work on Mullvad Browser, but it will take some time, and I'm as frustrated as you are.

So, please continue to report broken extension that you use daily, and the more reports we get, the more likely we are to look at it.

That being said, having all extension reports in the same thread is not a good way to track it. I'll create separate issues for each extensions and close this one.

**Comment by ruihildt** [comment] 2024-09-24 12:07
Related issue: https://github.com/mullvad/mullvad-browser/issues/274

**Comment by ruihildt** [comment] 2024-09-24 12:20
Metamask: #68 
PureVPN: #314
Memex: #316
NordVPN (not an extension issue it seems): #317

**Closed by ruihildt** 2024-09-24 12:20 UTC
Labels: third-party extension, webcompat

**Comment by ruihildt** [comment] 2024-09-24 13:08
@1z5q Would you mind next time opening a new issue?

I have created one for windscribe here: #319
