### ISSUE TITLE
Mullvad Browser on Android?

### ISSUE THREAD

**Issue by AverySalsedo21** [mullvad/mullvad-browser#338] opened 2024-10-20 15:08 UTC
Hi I'm thinking of moving to Mullvad on PC permanently cause I like it but was curious id you will be making an android app sometime in future or if its planned? Thanks , just curious

**Comment by Thorin-Oakenpants** [comment] 2024-10-21 01:49
dupe of #24

**Comment by ruihildt** [comment] 2024-10-21 08:24
It is planned, see #24

**Closed by ruihildt** 2024-10-21 08:24 UTC
Labels: duplicate
