### ISSUE TITLE
Mullvad Browser sometimes cannot load pages

### ISSUE THREAD

**Issue by PieroV** [mullvad/mullvad-browser#23] opened 2023-04-04 12:48 UTC
I think it's due to DoH, but I don't have actual steps to reproduce.
This problem is a bit random.

**Comment by fxbrit** [comment] 2023-04-05 21:58
@SkewedZeppelin it shouldn't be the case because OCSP is not set to hard-fail, plus when it fails it shows a relevant error message.

I also experienced connectivity issues earlier today while playing around with the browser, the error message is the generic one for unreachable URLs. I suppose it could be easier to reproduce the issue on a fresh start since then the DNS cache would be empty.

**Comment by Thorin-Oakenpants** [comment] 2023-04-06 00:16
Also happened to me on first start after unpacking. Since then it's been peachy

**Comment by ruihildt** [comment] 2023-05-09 20:59
Closing as no more information has been provided. It could simply be a DoH issue, and more DoH servers have now been deployed.

Feel free to open a new issue if needed.

**Closed by ruihildt** 2023-05-09 20:59 UTC
Labels: bug, doh

**Comment by xTkAx** [comment] 2023-12-13 04:36
Have replicated this problem today with _Mullvad 13.0.6_ [default settings] at the URL: 

https://finance.yahoo.com/quote/%5EDJI/

The status bar shows `finance.yahoo.com` and `guce.yahoo.com` flashing a few times, then the page says:

```
The page isn’t redirecting properly

An error occurred during a connection to finance.yahoo.com.

    This problem can sometimes be caused by disabling or refusing to accept cookies.
```

Following the same url on other browsers, using the same connection, displays the page as expected.

**Comment by PieroV** [comment] 2023-12-13 07:38
That happens also to me with Reddit, but I don't think it's related to DoH.
