### ISSUE TITLE
Interaction with Windows Hello for hardware key auth doesn't work

### ISSUE THREAD

**Issue by mattdale77** [mullvad/mullvad-browser#59] opened 2023-04-12 17:58 UTC
I don't know the area well enough to provide too many details but Skiff email have recently implemented 2Fa with hardware keys. On Windows it seems to use Windows Hello. In Librewolf when I click the button to set up it launches a Windows Hello window but in MB it does nothing at all so I would be unable to use this feature. This may be a deliberate policy but it would seem that being able to integrate with these authorisation channels should be something that works.

I'm raising this to find out if this is a bug or a feature.

**Comment by Thorin-Oakenpants** [comment] 2023-04-12 21:49
@ruihildt not my area - here's the sole ticket I could find upstream - https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/33849 - I suspect it's been disabled until they can get around to it

**Comment by mattdale77** [comment] 2023-04-13 07:26
Then it's probably worth tracking here as if this browser is going to be more mainstream than Tor Browser then this is going to be an issue that needs dealt with

**Comment by ruihildt** [comment] 2023-04-17 13:38
Looking at the ticket linked by @Thorin-Oakenpants , it seems Windows Hello is using WebAuthn.

Duplicate of #53

**Closed by ruihildt** 2023-04-17 13:38 UTC
Labels: duplicate
