### ISSUE TITLE
Feature request: built-in VPN in the browser to protect the traffic in the app (could be especially useful if portable browser is needed)

### ISSUE THREAD

**Issue by jan-kleks** [mullvad/mullvad-browser#279] opened 2024-07-11 00:07 UTC
Allow users to set up VPN directly in the browser. Let's say, you want to protect at least the traffic within the app when you are, for instance, in the library, by putting the browser on a USB stick like this: https://tb-manual.torproject.org/make-tor-portable/

**Comment by ruihildt** [comment] 2024-07-23 09:02
Closing as a duplicate of #103

**Closed by ruihildt** 2024-07-23 09:02 UTC
Labels: duplicate

**Comment by ioc2e3** [comment] 2025-06-25 21:40
Agreed ...

Hope can put Mullvad Browser on USB drive ...

.
