### ISSUE TITLE
Old browser profile missing after update!!!

### ISSUE THREAD

**Issue by NearestWater262** [mullvad/mullvad-browser#268] opened 2024-06-22 04:18 UTC
You guys are insane. I thought I had lost all my bookmarks and config and things. After careful inspection of the flatpak user data tree, I realized I could still recover my old profile.

Shame on you for doing this and scaring people! You should have migrated the profile or warned people somewhere!

Anyway, for those who are coming here and complaining as well, I will show you how to fix it 

1. Navigate in your File Manager to this directory: `/home/MYUSER/.var/app`  -  The .var folder is hidden, so you may have to press Ctrl+H or whatever it takes to show hidden folders
2. the Mullvad app data is inside the app data folder `/home/MYUSER/.var/app/net.mullvad.MullvadBrowser` **Copy this entire folder and paste it somewhere as backup in case you mess up!!**
3. now go inside the app data folder. you will see cache and config and such. you will see two folders, `.mullvad` which is the old folder with your old browser profile, and `.mullvad-browser` which is the new folder that now houses your profile. It seems that the devs change the folder where the profiles live.
4. You must first delete the new profile that was freshly created. So it will be at `/home/MYUSER/.var/app/net.mullvad.MullvadBrowser/.mullvad-browser/.mullvad/mullvadbrowser`. Inside this folder, there will be 3 items, a folder called `<something>.default-release` and 2 files called `installs.ini` and `profiles.ini`. Delete these three items.
5. Now you must copy the old profile to the place where the new profile was. So you will go to the folder `/home/MYUSER/.var/app/net.mullvad.MullvadBrowser/.mullvad/mullvadbrowser`. This is where you will see your old browser profile, safe and sound :)  copy the `<something>.default-release` folder and the 2 ini files, and paste them into the new browser profiles folder mentioned in Step 4 at `/home/MYUSER/.var/app/net.mullvad.MullvadBrowser/.mullvad-browser/.mullvad/mullvadbrowser`
6. Now you can start mullvad browser and see your old bookmarks and such

If you are using non-flatpak, then you will have to find where the user data folder is and do a similar process, but i do not where exactly where that folder is.

**Comment by ruihildt** [comment] 2024-06-22 08:03
This is a duplicate of https://github.com/mullvad/mullvad-browser/issues/265

According to the flatpak community maintainer, simply updating your flatpak to the latest version will take care of fixing this profile issue.

This issue doesn't affect non-flatpak installs, as far as we know.

We could have communicated better with the flatpak maintainer about this profile breaking change, and will make sure it doesn't happen again in the future.

**Closed by ruihildt** 2024-06-22 08:03 UTC

**Comment by NearestWater262** [comment] 2024-07-14 07:42
@ruihildt okay! thank you for commenting. Mullvad does amazing work, love the mullvad team!!
