### ISSUE TITLE
Mullvad Browser FoxyProxy not working

### ISSUE THREAD

**Issue by ruihildt** [mullvad/mullvad-browser#259] opened 2024-05-29 11:24 UTC
> I'm seemingly unable to connect to a HTTPS proxy using FoxyProxy on Mullvad Browser. Does Mullvad Browser not support third party proxies?

See: https://www.reddit.com/r/mullvadvpn/comments/1d2qdw8/mullvad_browser_foxyproxy_not_working/

**Comment by erosman** [comment] 2024-08-07 18:44
The issue is fixed in the next FoxyProxy release (v8.10).

See also: https://github.com/foxyproxy/browser-extension/issues/141#issuecomment-2274113550

**Closed** 2024-09-24 11:38 UTC
Labels: bug, third-party extension
