### ISSUE TITLE
usability: user confusion whether a VPN is used or not

### ISSUE THREAD

**Issue by adrelanos** [mullvad/mullvad-browser#232] opened 2024-03-09 14:41 UTC
Mullvad is well known a a VPN company. The name Mullvad is hard wired to VPN.

Now that there is a Mullvad Browser (MB), users assume that the browser comes with a VPN integrated by default.

It's not easy, if possible at all, for the Mullvad brand to maintain a browser privacy focused browser without causing confusion.

I am not sure what would be the way to fix this.

Mullvad customers will often assume and/or expect, that MB comes with Mullvad VPN by default. That is your heritage for being known a a VPN company. Related issue:

* https://github.com/mullvad/mullvad-browser/issues/4

Suggested solutions:

* A) separate project, logo
  * maintain a new brand,
  * a new, dedicated, separate domain name,
  * a new logo.
  * Without reference to Mullvad.
  * You can mention somewhere something like "Privacy Browser has been created by the same team that created Mullvad VPN." That's useful to leverage your exiting reputation but has to be done careful to avoid causing confusion.
* B) two different projects
  * Mullvad Browser (Mullvad VPN enabled by default)
  * Privacy Browser (no VPN integration by default)
* C) Mullvad extension improvements
  * by default, a red, crossed out VPN icon for Mullvad extension,
  * turning green, if Mullvad VPN is enabled
* D) A browser first start wizard.
  * Ask the user if the user wants to use it as Privacy Browser (no VPN integration) or as Mullvad Browser (refusing connections unless Mullvad VPN will be used)
* E) Default local browser homepage improvements.
  * Could show `Using Mullvad VPN:` `yes|no`

**Comment by ruvilonix** [comment] 2024-03-19 02:59
I'll add that I was a bit confused when I first downloaded the browser. I wasn't sure if the VPN was built in, and I needed to enter my Mullvad account number somewhere.

**Comment by ruihildt** [comment] 2024-04-02 12:20
While initially around release time we've seen some confusion regarding Mullvad Browser and whether it required to have a Mullvad VPN subscription, this hasn't been the case since then. Consequently, I'm not sure to what extent this is really an issue for users.

I expect over time that any confusion will subside even more.

**A/B/D** - There is no plan to change the project branding.

**C/E** - To establish whether you're connected to Mullvad VPN, the extension does a connection check, but this information is valid at the time of the check. Displaying anything in the UI constantly would require to have real time information.
An idea which could be worth pursuing would be to make a connection between Mullvad VPN app and the Mullvad Browser when the Mullvad VPN app is used.
But this is not currently planned, because improving the browser usability and defense against fingerprinting has a much higher priority.

Closing as a duplicate of #4

**Closed by ruihildt** 2024-04-02 12:20 UTC
Labels: duplicate, question
