### ISSUE TITLE
how get KeePassxc extension work in mullvad browser?

### ISSUE THREAD

**Issue by yourmother9** [mullvad/mullvad-browser#207] opened 2024-01-05 06:02 UTC
i download/install extension from https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/

in "Manage Your Extensions" list its seems te be activated but i can't do nothing.

it does not show up in toolbar.

oh i am a newbe and i am using linux mint.

**Comment by Tre-brock** [comment] 2024-01-06 14:23
You're not intended to use any extentions in the browser or change any settings because it will make your fingerprint unique, ruining the point of the browser

**Comment by yourmother9** [comment] 2024-01-07 08:25
> You're not intended to use any extentions in the browser or change any settings because it will make your fingerprint unique, ruining the point of the browser

so how do you get you usernames/passwords into the browser then?

**Comment by ruihildt** [comment] 2024-01-08 14:41
Duplicate of #55.

While I haven't tried connecting Mullvad Browser to KeepassXC, some people managed to do it.

**Closed by ruihildt** 2024-01-08 14:41 UTC
Labels: duplicate

**Comment by yourmother9** [comment] 2024-01-09 13:50
Hello @ruihildt  
so after re-install keepass extension its finally showsup in mullvad toolbar. 
i tried followd https://github.com/mullvad/mullvad-browser/issues/55. advice but i can't find  /mullvad-browser map. 
its does not exist... what strange because i use mullvad browser a little while now.  
no clue what to do now.
