### ISSUE TITLE
Add support to open magnetic links

### ISSUE THREAD

**Issue by Refold3547** [mullvad/mullvad-browser#336] opened 2024-10-15 03:14 UTC
There was a discussion last year on this topic in this link, and one of the reasons mentioned for not allowing this is due to the risk associated with tracking URLs: https://github.com/mullvad/mullvad-browser/issues/21

However, considering that MullvadBrowser is aimed at users with a less strict threat model and who perform common tasks when browsing the internet, such as watching videos or downloading torrents, I think there wouldn't be an issue in allowing this feature.

URL tracking can be minimized by making some configurations and adding filters in the uBlock extension. Additionally, the browser is set by default to delete all cookies when closed.

Although it's possible to copy the links and paste them directly into qbittorrent, this negatively affects the user experience for those using MullvadBrowser and may lead them to abandon the browser.

If it is not possible to enable this setting by default, could you at least include an option in the settings that would allow this feature? That way, the user would be aware of the risks involved, and the browser would maintain the same level of security as before.

**Comment by ruihildt** [comment] 2024-10-15 08:22
This is planned, here is the latest on it on the upstream repository: https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/219

Basically I agree with you, but we need to have someone look at it and review the Firefox implementation.

Closing as a duplicate of #21.

**Closed by ruihildt** 2024-10-15 08:22 UTC
