### ISSUE TITLE
Add arm64 support for Linux Raspberry Pi users

### ISSUE THREAD

**Issue by andyinthevalley** [mullvad/mullvad-browser#90] opened 2023-05-14 22:44 UTC
Both Firefox and Mullvad VPN work perfectly on arm64 on Ubuntu 64 bit.

It would be great if the Mullvad browser also worked there.

**Comment by simonrolfmore** [comment] 2024-01-12 15:52
Also useful for Asahi Linux on ARM Macs, now [Fedora Asahi Remix](https://asahilinux.org/fedora/?ref=upstract.com) is out :)

**Comment by ruihildt** [comment] 2024-01-23 12:50
Belatedly closing this as a duplicate of #11

**Closed by ruihildt** 2024-01-23 12:50 UTC
Labels: duplicate
