### ISSUE TITLE
Minimizing / Maximizing unavailable in native wayland mode

### ISSUE THREAD

**Issue by nzb-tuxxx** [mullvad/mullvad-browser#186] opened 2023-11-23 11:59 UTC
When running with MOZ_ENABLE_WAYLAND=1 (native wayland mode) minimizing and maximizing browser window disappears. There are only options to close the browser and to show all tabs. Maybe this is an issue with sandboxing?

![image](https://github.com/mullvad/mullvad-browser/assets/143939649/0c541daa-f25e-4910-83dd-a2b70d8e2ea5)

**Comment by nzb-tuxxx** [comment] 2023-11-28 15:11
Can confirm now. Trying to open mullvad extention sometimes leads to an instant crash. and some other times it just works

**Comment by ruihildt** [comment] 2024-09-19 11:39
I will close this as a duplicate of #136 , because we don't officially support Wayland and it hasn't been tested.

When Wayland will we supported, this bug will also have been fixed.

**Closed by ruihildt** 2024-09-19 11:39 UTC
Labels: duplicate
