### ISSUE TITLE
No compatible source was found for this media

### ISSUE THREAD

**Issue by Zepfanman** [mullvad/mullvad-browser#211] opened 2024-01-10 21:12 UTC
Not sure what is causing this error for the video player on this site. Same for Tor browser. https://player.eyefilm.nl/en/films/the-brilliant-biograph

**Comment by Thorin-Oakenpants** [comment] 2024-01-10 21:50
what is your OS? what are the error messages (control-shift-k) ? Often, but not always, the issue is missing codecs. FF + TB/MB can't ship proprietary codecs and rely on the OS. search this repo for fedora and codec issues for example

**Comment by Zepfanman** [comment] 2024-01-10 23:00
Error is "EME has been preffed off" which appears to be DRM settings that I can't change in Mullvad Browser? I'm on Windows 11 23H2. The video works fine in Firefox.

**Comment by Thorin-Oakenpants** [comment] 2024-01-10 23:31
There's your answer. Encryption Media Extension = DRM which is not (fully? any?) open source and certainly not a reproducible build. So TB/MB cannot ship it.

fyi: `media.eme.enabled` is the pref (and there's a UI pref as well). The pref isn't locked, but I'm pretty sure if you flipped it, it wouldn't be able to download - in FF if you flip the UI option it removes, re-downloads widevine

@pospeselr did we remove the ability for base browser to be able to download or use any "plugins"?

**Comment by ruihildt** [comment] 2024-01-12 13:32
DRM is currently not supported in Mullvad Browser.

This issue is a duplicate of #158

**Closed by ruihildt** 2024-01-12 13:32 UTC
Labels: duplicate
