### ISSUE TITLE
Support for Android .apk?

### ISSUE THREAD

**Issue by AItoid** [mullvad/mullvad-browser#288] opened 2024-07-29 16:46 UTC
I would like to switch to Mullvad's browser, but I'd like to use it on all devices such as computer, and smartphone.
Is there any plans on providing an Android .apk file for download to use Mullvad browser on the phone?
Thanks!

**Comment by redoomed1** [comment] 2024-07-30 04:13
Duplicate of #24

**Closed** 2024-07-30 07:17 UTC
Labels: duplicate
