### ISSUE TITLE
uBlock Origin "My filters" not working

### ISSUE THREAD

**Issue by yakumi9x** [mullvad/mullvad-browser#140] opened 2023-09-11 16:36 UTC
I use this custom filter rule in "My filters" in uBO to block telemetry on Discord:
`https://discord.com/api/v*/science`

This has always worked fine in all browsers I've used, but in Mullvad Browser it doesn't work: the request is not being blocked

To reproduce:
- Add that rule to "My filters"
- Open a new tab & open DevTools Network tab
- Navigate to discord.com
- Observe that the `science` request is not being blocked

**Comment by yakumi9x** [comment] 2023-09-11 16:44
I figured out just now why it's not working.
It's because the "My filters" filter list is disabled by default in the "Filter lists" tab.
Why is this the case? This is not default uBO behavior, that filter list is enabled by default when using uBO in other browsers.

**Comment by Thorin-Oakenpants** [comment] 2023-09-11 19:22
see #127 - this ->  the "My filters" filter list is disabled by default <- explains that

**Comment by ruihildt** [comment] 2023-10-06 11:34
Closing as duplicate of #127 .

**Closed by ruihildt** 2023-10-06 11:34 UTC
Labels: duplicate
